name: flutter_application_3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  -  images/azis.jpeg
  -  images/rm1.jpeg
  -  images/rm2.jpeg
  -  images/rm3.jpeg
  -  images/rm4.jpeg 
  -  images/rm5.jpeg
  -  images/ft1.jpg
  -  images/ft2.jpg
  -  images/ft3.jpg
